### ISSUE TITLE
S1 orbit data download

### ISSUE THREAD

**Issue by EJFielding** [bakerunavco/SSARA#10]
I was very happy to see the new feature added to download the Sentinel-1 orbit data with the actual SAR data download. It seems that it may not work for the "RESORB" data. I am trying to download the Sentinel-1 data over Ridgecrest from July 2019, and it successfully downloads the POEORB data for the earliest scenes but gives these errors, which I think are for the more recent RESORB dates.
`Downloading S1 orbit data, 6 at a time
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/home/fielding/scripts/ssara_federated_query.py", line 320, in run
    scene_center_time = datetime.datetime.strptime(scene['startTime'],"%Y-%m-%dT%H:%M:%S.%f")
AttributeError: _strptime

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/home/fielding/scripts/ssara_federated_query.py", line 320, in run
    scene_center_time = datetime.datetime.strptime(scene['startTime'],"%Y-%m-%dT%H:%M:%S.%f")
AttributeError: _strptime

Already downloaded http://aux.sentinel1.eo.esa.int/POEORB/2019/07/24/S1A_OPER_AUX_POEORB_OPOD_20190724T120636_V20190703T225942_20190705T005942.EOF
Already downloaded http://aux.sentinel1.eo.esa.int/POEORB/2019/07/24/S1A_OPER_AUX_POEORB_OPOD_20190724T120636_V20190703T225942_20190705T005942.EOF
`

**Comment by EJFielding** [comment]
I forgot to mention that the download process hangs after the exceptions described above. I have to kill it.
