### ISSUE TITLE
Error in downloading data

### ISSUE THREAD

**Issue by mohseniaref** [bakerunavco/SSARA#9]
Hi Scot,

Would you please help me to solve this error in downloading Envisat data?

best,
M
 ssara_federated_query.py --platform=ENVISAT -r 500 -f 729 --download
Running SSARA API Query
SSARA API query: 1.453669 seconds
Found 19 scenes
Scenes after filtering for monthMin 1 and monthMax 12: 19
Downloading data now, 1 at a time.
Downloading: https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDK20040726_184836_000000162028_00500_12578_2823.N1
ASA_IM__0CNPDK20040726_184836_000000162028_00500_12578_2823.N1 download time: 0.00 secs (95890.51 MB/sec)
Downloading: https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDE20041108_184832_000000172031_00500_14081_4143.N1
ASA_IM__0CNPDE20041108_184832_000000172031_00500_14081_4143.N1 download time: 0.00 secs (114170.61 MB/sec)
Downloading: https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDK20050117_184829_000000162033_00500_15083_8793.N1
ASA_IM__0CNPDK20050117_184829_000000162033_00500_15083_8793.N1 download time: 0.00 secs (122759.06 MB/sec)
Downloading: https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDK20050221_184829_000000162034_00500_15584_9800.N1
ASA_IM__0CNPDK20050221_184829_000000162034_00500_15584_9800.N1 download time: 0.00 secs (126084.86 MB/sec)
Downloading: https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDK20050502_184837_000000162036_00500_16586_1577.N1
ASA_IM__0CNPDK20050502_184837_000000162036_00500_16586_1577.N1 download time: 0.00 secs (121689.11 MB/sec)
Downloading: https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDK20050606_184835_000000162037_00500_17087_0343.N1
ASA_IM__0CNPDK20050606_184835_000000162037_00500_17087_0343.N1 download time: 0.00 secs (113901.54 MB/sec)
Downloading: https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDE20050815_184832_000000172039_00500_18089_1079.N1
ASA_IM__0CNPDE20050815_184832_000000172039_00500_18089_1079.N1 download time: 0.00 secs (118878.83 MB/sec)
Downloading: https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDK20051128_184829_000000162042_00500_19592_4034.N1
ASA_IM__0CNPDK20051128_184829_000000162042_00500_19592_4034.N1 download time: 0.00 secs (107748.39 MB/sec)
Downloading: https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDK20060102_184821_000000172043_00500_20093_0113.N1
ASA_IM__0CNPDK20060102_184821_000000172043_00500_20093_0113.N1 download time: 0.00 secs (109896.95 MB/sec)
Downloading: http://eogrid.esrin.esa.int/download/ASA_IM__0P/2006/05/22/ASA_IM__0PNPDE20060522_184820_000000182047_00500_22097_3013.N1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/earth/Software/dlscript/ssara_federated_query.py", line 435, in run
    va4_dl(d,opt_dict)
  File "/home/earth/Software/dlscript/ssara_federated_query.py", line 418, in va4_dl
    mb_sec = (os.path.getsize(filename) / (1024 * 1024.0)) / total_time
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'ASA_IM__0PNPDE20060522_184820_000000182047_00500_22097_3013.N1'

**Comment by suiuy** [comment]
i also met the same and couldn't solve it. do you solve it?
